return {
  diagnostics = {
    error = " ",
    warn = " ",
    info = " ",
    hint = "󰌵 ",
  },
  types = {
    Array = "󰅪 ",
    Boolean = "◩ ",
    Color = "󰏘 ",
    Constant = "󰏿 ",
    Constructor = " ",
    Class = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = "󰊕 ",
    Interface = " ",
    Key = "󰌋 ",
    Keyword = "󰌋 ",
    Method = "󰆧 ",
    Module = " ",
    Namespace = " ",
    Null = "󰟢 ",
    Number = "󰎠 ",
    Object = "󰅩 ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = "󰈇 ",
    Snippet = " ",
    String = "󰀬 ",
    Struct = " ",
    Text = "󰀬 ",
    TypeParameter = " ",
    Unit = "󰑭 ",
    Value = "󰎠 ",
    Variable = "󰀫 ",
  },
}
