return {
  cmp_sources = {
    buffer = " ",
    cmdline = " ",
    dap = " ",
    emmet_vim = "󰕣 ",
    fish = "󰈺 ",
    git = "󰊢 ",
    luasnip = " ",
    nvim_lsp = " ",
    nvim_lsp_signature_help = "󰷻 ",
    path = " ",
    vimtex = " ",
  },
  debug = {
    breakpoint = {
      normal = " ",
      conditional = " ",
      log = " ",
      rejected = " ",
    },
    current_frame = " ",
  },
  diagnostics = {
    indicator = "■",
    severities = {
      error = " ",
      warn = " ",
      info = " ",
      hint = "󰌵 ",
    },
  },
  files = {
    modified = " ",
    readonly = "",
    unnamed = "",
    newfile = " ",
  },
  fillchars = {
    diff = " ",
  },
  git = {
    lines = {
      added = "󰐕",
      deleted = "󰍴",
      modified = "",
      removed = "󰍴",
    },
    files = {
      conflict = " ",
      ignored = " ",
      renamed = " ",
      staged = " ",
      unstaged = "󰄱 ",
      untracked = "",
    },
  },
  log = {
    error = " ",
    warn = " ",
    info = " ",
    debug = " ",
    trace = " ",
  },
  separators = {
    section = {
      bottom = {
        left = "",
        right = "",
      },
      top = {
        left = "",
        right = "",
      },
    },
    component = {
      bottom = {
        left = "",
        right = "",
      },
      top = {
        left = "",
        right = "",
      },
    },
    hierarchy = {
      right = "",
    },
  },
  snippet = {
    choice_virt_text = " ",
    insert_virt_text = "…",
  },
  todo = {
    fix = " ",
    todo = " ",
    hack = " ",
    warn = " ",
    perf = " ",
    note = " ",
    test = "⏲ ",
  },
  types = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = "󰏿 ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = "󰊕 ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = "󰆧 ",
    Module = " ",
    Namespace = " ",
    Null = " ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = "󰀬 ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = "󰀫 ",
  },
}
