return {
  cmp_sources = {
    buffer = " ",
    cmdline = " ",
    dap = " ",
    fish = "󰈺 ",
    git = "󰊢 ",
    luasnip = " ",
    nvim_lsp = " ",
    path = " ",
    vimtex = " ",
  },
  debug = {
    breakpoint = {
      normal = " ",
      conditional = " ",
      log = " ",
      rejected = " ",
    },
    current_frame = " ",
  },
  diagnostics = {
    error = " ",
    warn = " ",
    info = " ",
    hint = "󰌵 ",
  },
  files = {
    modified = " ",
    readonly = "",
    unnamed = "",
    newfile = " ",
  },
  git = {
    lines = {
      added = "󰐕",
      deleted = "󰍴",
      modified = "",
      removed = "󰍴",
    },
    files = {
      conflict = " ",
      ignored = " ",
      renamed = " ",
      staged = " ",
      unstaged = "󰄱 ",
      untracked = "",
    },
  },
  separators = {
    level1 = {
      left = "",
      right = "",
    },
    level2 = {
      left = "│",
      right = "│",
    },
  },
  types = {
    Array = "󰅪 ",
    Boolean = "◩ ",
    Class = " ",
    Color = "󰏘 ",
    Constant = "󰏿 ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = "󰊕 ",
    Interface = " ",
    Key = "󰌋 ",
    Keyword = " ",
    Method = "󰆧 ",
    Module = " ",
    Namespace = " ",
    Null = "󰟢 ",
    Number = "󰎠 ",
    Object = "󰅩 ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = "󰈇 ",
    Snippet = " ",
    String = "󰀬 ",
    Struct = " ",
    Text = "󰀬 ",
    TypeParameter = " ",
    Unit = " ",
    Value = "󰎠 ",
    Variable = "󰀫 ",
  },
}
