require("neodev").setup {
  library = {
    plugins = {
      "LuaSnip",
      "cmp-buffer",
      "cmp-cmdline",
      "cmp-git",
      "cmp-nvim-lsp",
      "cmp-path",
      "cmp_luasnip",
      "dressing.nvim",
      "gitsigns.nvim",
      "lspkind.nvim",
      "lualine.nvim",
      "mason-lspconfig.nvim",
      "mason.nvim",
      "null-ls.nvim",
      "nvim-cmp",
      "nvim-colorizer",
      "nvim-dap",
      "nvim-dap-ui",
      "nvim-jdtls",
      "nvim-lspconfig",
      "nvim-luapad",
      "nvim-notify",
      "nvim-tree.lua",
      "nvim-treesitter",
      "nvim-treesitter-context",
      "playground",
      "plenary.nvim",
      "telescope-fzf-native.nvim",
      "telescope.nvim",
      "twilight.nvim",
      "typescript.nvim",
      "zen-mode.nvim",
    },
    types = true,
  },
}
